# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connectivity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='connectivity.proto',
  package='spotify.clienttoken.data.v0',
  syntax='proto3',
  serialized_options=b'\n\037com.spotify.clienttoken.data.v0H\002',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63onnectivity.proto\x12\x1bspotify.clienttoken.data.v0\"{\n\x13\x43onnectivitySdkData\x12Q\n\x16platform_specific_data\x18\x01 \x01(\x0b\x32\x31.spotify.clienttoken.data.v0.PlatformSpecificData\x12\x11\n\tdevice_id\x18\x02 \x01(\t\"\xdf\x01\n\x14PlatformSpecificData\x12\x41\n\x07\x61ndroid\x18\x01 \x01(\x0b\x32..spotify.clienttoken.data.v0.NativeAndroidDataH\x00\x12\x39\n\x03ios\x18\x02 \x01(\x0b\x32*.spotify.clienttoken.data.v0.NativeIOSDataH\x00\x12\x41\n\x07windows\x18\x04 \x01(\x0b\x32..spotify.clienttoken.data.v0.NativeWindowsDataH\x00\x42\x06\n\x04\x64\x61ta\"\xb9\x01\n\x11NativeAndroidData\x12\x19\n\x11major_sdk_version\x18\x01 \x01(\x05\x12\x19\n\x11minor_sdk_version\x18\x02 \x01(\x05\x12\x19\n\x11patch_sdk_version\x18\x03 \x01(\x05\x12\x13\n\x0b\x61pi_version\x18\x04 \x01(\r\x12>\n\x11screen_dimensions\x18\x05 \x01(\x0b\x32#.spotify.clienttoken.data.v0.Screen\"\x9e\x01\n\rNativeIOSData\x12\x1c\n\x14user_interface_idiom\x18\x01 \x01(\x05\x12\x1f\n\x17target_iphone_simulator\x18\x02 \x01(\x08\x12\x12\n\nhw_machine\x18\x03 \x01(\t\x12\x16\n\x0esystem_version\x18\x04 \x01(\t\x12\"\n\x1asimulator_model_identifier\x18\x05 \x01(\t\"\xa0\x01\n\x11NativeWindowsData\x12\x12\n\nsomething1\x18\x01 \x01(\x05\x12\x12\n\nsomething3\x18\x03 \x01(\x05\x12\x12\n\nsomething4\x18\x04 \x01(\x05\x12\x12\n\nsomething6\x18\x06 \x01(\x05\x12\x12\n\nsomething7\x18\x07 \x01(\x05\x12\x12\n\nsomething8\x18\x08 \x01(\x05\x12\x13\n\x0bsomething10\x18\n \x01(\x08\"8\n\x06Screen\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x0f\n\x07\x64\x65nsity\x18\x03 \x01(\x05\x42#\n\x1f\x63om.spotify.clienttoken.data.v0H\x02\x62\x06proto3'
)




_CONNECTIVITYSDKDATA = _descriptor.Descriptor(
  name='ConnectivitySdkData',
  full_name='spotify.clienttoken.data.v0.ConnectivitySdkData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='platform_specific_data', full_name='spotify.clienttoken.data.v0.ConnectivitySdkData.platform_specific_data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='spotify.clienttoken.data.v0.ConnectivitySdkData.device_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=174,
)


_PLATFORMSPECIFICDATA = _descriptor.Descriptor(
  name='PlatformSpecificData',
  full_name='spotify.clienttoken.data.v0.PlatformSpecificData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='android', full_name='spotify.clienttoken.data.v0.PlatformSpecificData.android', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ios', full_name='spotify.clienttoken.data.v0.PlatformSpecificData.ios', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='windows', full_name='spotify.clienttoken.data.v0.PlatformSpecificData.windows', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='spotify.clienttoken.data.v0.PlatformSpecificData.data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=177,
  serialized_end=400,
)


_NATIVEANDROIDDATA = _descriptor.Descriptor(
  name='NativeAndroidData',
  full_name='spotify.clienttoken.data.v0.NativeAndroidData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='major_sdk_version', full_name='spotify.clienttoken.data.v0.NativeAndroidData.major_sdk_version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='minor_sdk_version', full_name='spotify.clienttoken.data.v0.NativeAndroidData.minor_sdk_version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='patch_sdk_version', full_name='spotify.clienttoken.data.v0.NativeAndroidData.patch_sdk_version', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='api_version', full_name='spotify.clienttoken.data.v0.NativeAndroidData.api_version', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='screen_dimensions', full_name='spotify.clienttoken.data.v0.NativeAndroidData.screen_dimensions', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=588,
)


_NATIVEIOSDATA = _descriptor.Descriptor(
  name='NativeIOSData',
  full_name='spotify.clienttoken.data.v0.NativeIOSData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_interface_idiom', full_name='spotify.clienttoken.data.v0.NativeIOSData.user_interface_idiom', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_iphone_simulator', full_name='spotify.clienttoken.data.v0.NativeIOSData.target_iphone_simulator', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hw_machine', full_name='spotify.clienttoken.data.v0.NativeIOSData.hw_machine', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='system_version', full_name='spotify.clienttoken.data.v0.NativeIOSData.system_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='simulator_model_identifier', full_name='spotify.clienttoken.data.v0.NativeIOSData.simulator_model_identifier', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=749,
)


_NATIVEWINDOWSDATA = _descriptor.Descriptor(
  name='NativeWindowsData',
  full_name='spotify.clienttoken.data.v0.NativeWindowsData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='something1', full_name='spotify.clienttoken.data.v0.NativeWindowsData.something1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='something3', full_name='spotify.clienttoken.data.v0.NativeWindowsData.something3', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='something4', full_name='spotify.clienttoken.data.v0.NativeWindowsData.something4', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='something6', full_name='spotify.clienttoken.data.v0.NativeWindowsData.something6', index=3,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='something7', full_name='spotify.clienttoken.data.v0.NativeWindowsData.something7', index=4,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='something8', full_name='spotify.clienttoken.data.v0.NativeWindowsData.something8', index=5,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='something10', full_name='spotify.clienttoken.data.v0.NativeWindowsData.something10', index=6,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=752,
  serialized_end=912,
)


_SCREEN = _descriptor.Descriptor(
  name='Screen',
  full_name='spotify.clienttoken.data.v0.Screen',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='spotify.clienttoken.data.v0.Screen.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='spotify.clienttoken.data.v0.Screen.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='density', full_name='spotify.clienttoken.data.v0.Screen.density', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=914,
  serialized_end=970,
)

_CONNECTIVITYSDKDATA.fields_by_name['platform_specific_data'].message_type = _PLATFORMSPECIFICDATA
_PLATFORMSPECIFICDATA.fields_by_name['android'].message_type = _NATIVEANDROIDDATA
_PLATFORMSPECIFICDATA.fields_by_name['ios'].message_type = _NATIVEIOSDATA
_PLATFORMSPECIFICDATA.fields_by_name['windows'].message_type = _NATIVEWINDOWSDATA
_PLATFORMSPECIFICDATA.oneofs_by_name['data'].fields.append(
  _PLATFORMSPECIFICDATA.fields_by_name['android'])
_PLATFORMSPECIFICDATA.fields_by_name['android'].containing_oneof = _PLATFORMSPECIFICDATA.oneofs_by_name['data']
_PLATFORMSPECIFICDATA.oneofs_by_name['data'].fields.append(
  _PLATFORMSPECIFICDATA.fields_by_name['ios'])
_PLATFORMSPECIFICDATA.fields_by_name['ios'].containing_oneof = _PLATFORMSPECIFICDATA.oneofs_by_name['data']
_PLATFORMSPECIFICDATA.oneofs_by_name['data'].fields.append(
  _PLATFORMSPECIFICDATA.fields_by_name['windows'])
_PLATFORMSPECIFICDATA.fields_by_name['windows'].containing_oneof = _PLATFORMSPECIFICDATA.oneofs_by_name['data']
_NATIVEANDROIDDATA.fields_by_name['screen_dimensions'].message_type = _SCREEN
DESCRIPTOR.message_types_by_name['ConnectivitySdkData'] = _CONNECTIVITYSDKDATA
DESCRIPTOR.message_types_by_name['PlatformSpecificData'] = _PLATFORMSPECIFICDATA
DESCRIPTOR.message_types_by_name['NativeAndroidData'] = _NATIVEANDROIDDATA
DESCRIPTOR.message_types_by_name['NativeIOSData'] = _NATIVEIOSDATA
DESCRIPTOR.message_types_by_name['NativeWindowsData'] = _NATIVEWINDOWSDATA
DESCRIPTOR.message_types_by_name['Screen'] = _SCREEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectivitySdkData = _reflection.GeneratedProtocolMessageType('ConnectivitySdkData', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIVITYSDKDATA,
  '__module__' : 'connectivity_pb2'
  # @@protoc_insertion_point(class_scope:spotify.clienttoken.data.v0.ConnectivitySdkData)
  })
_sym_db.RegisterMessage(ConnectivitySdkData)

PlatformSpecificData = _reflection.GeneratedProtocolMessageType('PlatformSpecificData', (_message.Message,), {
  'DESCRIPTOR' : _PLATFORMSPECIFICDATA,
  '__module__' : 'connectivity_pb2'
  # @@protoc_insertion_point(class_scope:spotify.clienttoken.data.v0.PlatformSpecificData)
  })
_sym_db.RegisterMessage(PlatformSpecificData)

NativeAndroidData = _reflection.GeneratedProtocolMessageType('NativeAndroidData', (_message.Message,), {
  'DESCRIPTOR' : _NATIVEANDROIDDATA,
  '__module__' : 'connectivity_pb2'
  # @@protoc_insertion_point(class_scope:spotify.clienttoken.data.v0.NativeAndroidData)
  })
_sym_db.RegisterMessage(NativeAndroidData)

NativeIOSData = _reflection.GeneratedProtocolMessageType('NativeIOSData', (_message.Message,), {
  'DESCRIPTOR' : _NATIVEIOSDATA,
  '__module__' : 'connectivity_pb2'
  # @@protoc_insertion_point(class_scope:spotify.clienttoken.data.v0.NativeIOSData)
  })
_sym_db.RegisterMessage(NativeIOSData)

NativeWindowsData = _reflection.GeneratedProtocolMessageType('NativeWindowsData', (_message.Message,), {
  'DESCRIPTOR' : _NATIVEWINDOWSDATA,
  '__module__' : 'connectivity_pb2'
  # @@protoc_insertion_point(class_scope:spotify.clienttoken.data.v0.NativeWindowsData)
  })
_sym_db.RegisterMessage(NativeWindowsData)

Screen = _reflection.GeneratedProtocolMessageType('Screen', (_message.Message,), {
  'DESCRIPTOR' : _SCREEN,
  '__module__' : 'connectivity_pb2'
  # @@protoc_insertion_point(class_scope:spotify.clienttoken.data.v0.Screen)
  })
_sym_db.RegisterMessage(Screen)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
